file_format: "1"
id: microbox34
name: Microbox34
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires:
  - pro_micro
features:
  - keys
siblings:
  - microbox34_left
  - microbox34_right