file_format: "1"
id: butterfly36
name: Butterfly36
type: shield
url: https://github.com/Bastardkb/Skeletyl
requires:
  - pro_micro
features:
  - keys
siblings:
  - butterfly36_left
  - butterfly36_right